name: simple_multiselect
description: "A Flutter package for simple creating multi select widgets."
version: 1.0.0
homepage:

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
