name: simple_multiselect
description: "A Flutter package for simple creating multi select widgets. The field refresh real-time on tap the list element."
version: 0.1.1
repository: https://github.com/icas711/simple_multiselect

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter: