name: simple_multiselect
description: "A Flutter package for simple creating multi select widgets."
version: 0.0.1
homepage:

environment:
  sdk: ^3.7.0-312.0.dev
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
